[project]
name = "py-aliasing"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "mxt", email = "mxnd.taylor@gmail.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.build]
excludes = ['**/example.py']

[tool.pdm.scripts]
examples = "python -m py_aliasing.example"
test = "pytest"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.2.1",
    "black>=24.4.2",
]
