# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "release/**" ]

jobs:
  pypi-publish:
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v3
    - name: Build
      run: pdm build
    - name: Update git release tag
      run: pdm bump tag
    - name: Test and get reports
      run: pdm reports
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: false
        draft: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: |
        # build artifacts
          dist/*
        # badges
          badges/*.svg
        # reports
          reports/junit/junit.xml
          reports/coverage/coverage.xml
          reports/flake8/stats.txt
        # html reports
          reports/junit/report.html
          reports/coverage/html/index.html
          reports/flake8/html/index.html
    - name: Publish package distributions to PyPI
      run: pdm publish --no-build
