name: Publish release

on:
  push:
    branches: [ "release/**" ]

jobs:
  pypi-publish:
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v3
    - name: Build
      run: pdm build
    - name: Update git release tag
      run: |
        git config --global user.name 'Auto'
        git config --global user.email 'mxndtaylor@users.noreply.github.com'
        pdm bump tag
        git push --tags
    - name: Test and get reports
      run: pdm reports
    - uses: "marvinpinto/action-automatic-releases@latest"
      id: gh-release
      with:
        prerelease: false
        draft: true
        automatic_release_tag: latest
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: |
          dist/*
          badges/*.svg
          reports/junit/junit.xml
          reports/coverage/coverage.xml
          reports/flake8/stats.txt
          reports/junit/report.html
          reports/coverage/html/index.html
          reports/flake8/html/index.html
    - name: Check Version Format
      if: ${{ startsWith(steps.gh-release.outputs.automatic_releases_tag, 'v') }}
      id: check-version
      run: |
        if [[ ${{ steps.gh-release.outputs.automatic_releases_tag }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version-type=release" >> $GITHUB_OUTPUT
        else
            echo "version-type=pre-release" >> $GITHUB_OUTPUT
        fi
    - name: Publish package distributions to PyPI
      # only run if it's not alpha, beta or a release candidate
      if: ${{ steps.check-version.outputs.version-type == 'release' }}
      run: pdm publish --no-build
