# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "release/**" ]

jobs:
  pypi-publish:
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: pdm-project/setup-pdm@v3
    - name: Test and get coverage report with pdm
      run: pdm coverage
    - name: Publish package distributions to PyPI
      run: pdm publish
